### ISSUE TITLE
Installation problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by batukav** [TinkerTools/tinker-openmm#1]
Dear All,

I'm trying to install the tinker-openmm interface on Ubuntu 20.04. I have followed the installation instructions without facing any problems, until the step "(6) Run the "make" command to build executables. When the build is finished, there will be three executables produced in the build directory, "analyze_omm.x", "bar_omm.x" and "dynamic_omm.x". "

The make command gives the following error:

gfortran -c -Ofast -msse3 -fopenmp ommdata.f -o ommdata.o
ommdata.f:100:44:

  100 |      &                     ybox2,zbox2,box23,volbox,alpha_sin,alpha_cos,
      |                                            1
Error: Symbol ‘box23’ at (1) has no IMPLICIT type; did you mean ‘box34’?
make: *** [Makefile:730: ommdata.o] Error 1

My gfortran, gcc, and g++ versions are 9.4.0. The installed OpenMM version is 7.5.0. I am also using the CUDA v11.4, if this is relevant.

Could anyone help me navigate this problem?

Thank you all.

**Comment by jayponder** [comment]
Hi, Sorry for the problem. We recently updated some files related to using OpenMM under Tinker, and missed changing this variable name in one of the source files. As the error you provide above indicates, you can just change "box23" to "box34" in the source file "ommdata.f". Alternatively, this change has just been updated in the Tinker repo at github/TinkerTools/tinker, so you can get a new version of Tinker with the correction there. (This correction is not yet propagated to the Tinker version on dasher.wustl.edu, and may not show up there for a few days.)

As indicated on the Tinker-OpenMM Github site, our Tinker-OpenMM interface is currently (still..) incompatible with changes the OpenMM developers made to their implementation of the AMOEBA force field in spring of this year. So you will need to get an older commit of OpenMM to build Tinker-OpenMM. We hope to get this updated and resolved at some point, but I'm not sure when it will happen (nobody is currently working on it..). If you wish to use AMOEBA on GPUs, I might suggest that you switch to the new Tinker9 code, available on Github from TinkerTools/Tinker9.
