### ISSUE TITLE
'''There is no registered Platform called "CUDA"''' ERROR with cuda_8.0_9.2_10.0_10.2

### ISSUE THREAD

**Issue by z5476t4508** [TinkerTools/Tinker-OpenMM#10]
Dear all,

I tried to build dynamic_omm on my server following the instructions on Prof. Ren's website (https://biomol.bme.utexas.edu/tinkergpu/index.php?title=Tinkergpu:Openmm-install) and Prof. Lee-Ping Wang's notes. 

Although all installation procedure passed correctly, I got the following error when I ran a test:

 _Andersen Thermostat:

 Target Temperature            300.00 K
 Collision Frequency    1.0000000e-01 ps^(-1)
 Random Number Seed                 0
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  There is no registered Platform called "CUDA"

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7FE20EDAB697
#1  0x7FE20EDABCDE
#2  0x7FE20E07A3AF
#3  0x7FE20E07A337
#4  0x7FE20E07BA27
#5  0x7FE210BA17D4
#6  0x7FE210B9F745
#7  0x7FE210B9F772
#8  0x7FE210B9F992
#9  0x7FE211203C8A
#10  0x7FE21132ACA1
#11  0x4095E2
#12  0x4125E3
#13  0x4086BB
#14  0x407B1C
#15  0x7FE20E066504
#16  0x407BAB
#17  0xFFFFFFFFFFFFFFFF
./run.sh: 行 2: 29313 已放弃               (吐核)nohup dynamic_omm eqnvt.xyz 10000 1.0 0.2 2 300.0 N > eqnvt.out_

Could you please give me some guidance? That means a lot to our work. 

The software environment of my server is:
OS: CentOS 7.7
Compiler: GCC 4.8.5
CUDA version: 8.0, 9.2, 10.0, 10.1, 10.2 (I tried all of these cuda versions, but got the same error)

The latest Tinker and Tinker-Openmm were cloned from the Github. 

Thank you so much for your help!

Best,
Tong

**Comment by z5476t4508** [comment]
Sorry I forgot to post the hardware  information, which are:

CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
GPU: GTX 1080
Information from running the nvidia-smi command:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   27C    P0    39W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:03:00.0 Off |                  N/A |
| 21%   31C    P0    40W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 00000000:82:00.0 Off |                  N/A |
| 22%   30C    P0    39W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 00000000:83:00.0 Off |                  N/A |
| 21%   27C    P0    38W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

And the CPU version of Tinker works fine. 

Thank you very much!
Tong

**Comment by zjing7** [comment]
Did you compile and run the program on the same machine and using the same environment variables?

**Comment by pren** [comment]
Try cuda 10.0.

**Comment by z5476t4508** [comment]
Dear Prof. Ren and zjing7,

I re-installed the OS (latest version of Centos7), and installed the cuda-10.0 and nvidia driver (version 418.104).

But after compiled Tinker I still have the same problem. 

The information about the hardware and env of the current machine are:

Cuda: 10.0 (which is the only cuda installed on this machine)
GCC: 4.8.5
Python 2.7.5

Information given by the nvidia-smi command:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:03:00.0  On |                  N/A |
| 28%   27C    P8     6W / 180W |     53MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      3127      G   /usr/bin/X                                    39MiB |
|    0      3827      G   /usr/bin/gnome-shell                          11MiB |
+-----------------------------------------------------------------------------+



After compiled Tinker-OpenMM, I ran "make test". Here is the last few lines in the log file. 

99% tests passed, 1 tests failed out of 420

Total Test time (real) = 3292.13 sec

The following tests FAILED:
        154 - TestOpenCLAndersenThermostatMixed (Failed)



Could you please give me some help?

Best,
Tong

**Comment by pren** [comment]
Please turn off irrelevant options such as opencl. See the example Cmakeoption.txt on https://biomol.bme.utexas.edu/tinkergpu/index.php?title=Tinkergpu:Openmm-install

**Comment by z5476t4508** [comment]
Dear Prof. Ren,

Now it works! 

Many thanks!

Tong
